### ISSUE TITLE
TCheckgroup Index out of bounds

### ISSUE THREAD

**Issue by rchastain** [DomingoGP/lazIdeDiffCompareFiles#1]
Hello!

I have just installed the package on Lazarus 2.2.4 and, when I click on _Tools/Diff compare files..._ I get this error message.

![diff-compare-tcheckgroup-index-cropped](https://user-images.githubusercontent.com/13957204/218002544-3fe99c3e-046f-47da-9d51-bf2101d4c85f.png)

Regards.

Roland

**Comment by DomingoGP** [comment]
Thanks for reporting,

I can reproduce also in lazarus 2.2.2  the last commit (4ecb7e04521bba239c0b1f4cd06837de0b79a5fa) solves the issue for me.
Please test.

Regards.
Domingo

**Comment by rchastain** [comment]
Yes, it is solved. Thanks!

I close the issue. See you!
